language: rust

rust:
  - stable

before_script:
  - rustup component add rustfmt  

script:
  - cargo fmt --all -- --check
  - cargo test --all
  - cargo test --all --features "small_branch"
  - cargo test --benches --features=arc,rayon-iter
  - cd pvec-memory && sh bench.sh
