[workspace]
members = ["pvec-core", "pvec-utils"]

[package]
name = "pvec"
version = "0.1.0"
authors = ["Araz Abishov <araz@abishov.com>"]

[dependencies]
pvec-core = { version = "0.1.0", path = "pvec-core" }
pvec-utils = { version = "0.1.0", path = "pvec-utils" }
rayon = { version = "1.1.0", optional = true }

[dev-dependencies]
im = { git = "https://github.com/bodil/im-rs" }
criterion = "0.3"
dogged = "0.2.0"
num = "0.2.0"
rand = "0.6"
rand_xorshift = "0.1"

[features]
serde-serializer = ["pvec-core/serde-serializer"]
rayon-iter = ["pvec-core/rayon-iter", "rayon"]
arc = ["pvec-core/arc", "pvec-utils/arc",]
small_branch = []

[[bench]]
name = "lib"
harness = false
