[workspace]
members = ["pvec-core", "pvec-utils"]

[package]
name = "pvec"
version = "0.1.0"
authors = ["Araz Abishov <araz@abishov.com>"]

[dependencies]
pvec-core = { version = "0.1.0", path = "pvec-core" }
pvec-utils = { version = "0.1.0", path = "pvec-utils" }

[dev-dependencies]
criterion = "0.2.10"
rand = "0.3.14"
dogged = "0.2.0"
im = { git = "https://github.com/bodil/im-rs" }

[features]
default = []
small_branch = []
arc = []
rayon-iter = []
serde-serializer = []

[[bench]]
name = "lib"
harness = false
