[workspace]
members = ["pvec-core", "pvec-utils"]

[package]
name = "pvec"
version = "0.1.0"
authors = ["Araz Abishov <araz@abishov.com>"]

[dependencies]
pvec-core = { version = "0.1.0", path = "pvec-core" }
pvec-utils = { version = "0.1.0", path = "pvec-utils" }
rayon = { version = "1.1.0", optional = true }

[dev-dependencies]
im = { git = "https://github.com/bodil/im-rs" }
rand_xorshift = "0.1"
criterion = "0.2.10"
dogged = "0.2.0"
num = "0.2.0"
docopt = "1"
rand = "0.6"
time = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = []
rayon-iter = ["pvec-core/rayon-iter", "rayon"]
arc = ["pvec-core/arc", "pvec-utils/arc",]
serde-serializer = []
small_branch = []

[[bench]]
name = "lib"
harness = false
