name: Build and test pvec-rs

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --features "small_branch"
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --benches --features=arc,rayon-iter
      - name: Run memory benches as tests
        run: sh bench.sh
        working-directory: pvec-memory
