name: build
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.41.1
          components: rustfmt, clippy
          override: true
      - uses: actions-rs/cargo@v1
        name: Checking code style
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: Running unit tests for the large branching factor
        with:
          command: test
          args: --all
      - uses: actions-rs/cargo@v1
        name: Running unit tests for the small branching factor
        with:
          command: test
          args: --all --features "small_branch"
      - uses: actions-rs/cargo@v1
        name: Running benchmarks as tests
        with:
          command: test
          args: --benches --features=arc,rayon-iter
      - name: Running memory benchmarks as tests
        run: sh bench.sh
        working-directory: pvec-memory
